# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
    nodePort: 30080  # This is the port on which the service will be exposed on the node
  selector:
    app: go-web-app
  type: NodePort
